service: mintable-app
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
      Resource: "arn:aws:dynamodb:ap-southeast-1:273533229813:table/NFTs"
functions:
  app:
    handler: dist/app.handler
    timeout: 15  # time in seconds
    events:
      - http: ANY /
      - http: ANY /{proxy+}
plugins: [
  'serverless-offline'
]

